name: Split JSON

on:
  push:
    paths:
      - "tokens.json"
  workflow_dispatch:

jobs:
  split-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Fetch recent commits
        run: git fetch origin main --depth=2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Create output folder
        run: mkdir -p output_json

      - name: Run Python script
        run: python split_json.py

      - name: Verify output
        run: ls -la output_json/

      - name: Zip output folder
        run: |
          cd output_json
          zip -r output_json.zip . -x output_json.zip

      - name: Verify zipped file
        run: ls -la output_json/

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        id: commit_changes
        run: |
          git add output_json || echo "No changes to commit"
          git diff --staged --quiet || git commit -m "Add split JSON files and zipped archive"
          git push origin main

      - name: Generate tokens.json diff summary
        id: token_diff
        run: |
          # Compare using the commit before this push and the current commit.
          # Using github.event.before from the push event:
          DIFF=$(git diff ${{ github.event.before }} ${{ github.sha }} -- tokens.json)
          if [ -z "$DIFF" ]; then
            echo "diff_summary=No changes in tokens.json" >> $GITHUB_OUTPUT
          else
            echo "diff_summary<<EOF" >> $GITHUB_OUTPUT
            echo "$DIFF" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi



      - name: Send Slack Notification
        if: success() && github.ref == 'refs/heads/main'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"New token updates!\n\nDownload the latest JSON zip file: <https://github.com/steant/hds-tokens/raw/main/output_json/output_json.zip|Download JSON Zip>\n\n<https://steant.github.io/hds-tokens/|HDS Token list>\n\n${{ github.event.head_commit.message }}\n\nChanges in tokens.json:\n${{ steps.token_diff.outputs.diff_summary }}\"}" \
            $SLACK_WEBHOOK_URL
